# Welcome to Jekyll!

# Site settings
title: "Alanah and Tom"
description: |
  October 8
owner: Aaron Monger
first_published: 2022 # if migrating another site, the year of your first publish
email: allymonger@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mycoyne.net" # the base hostname & protocol for your site

google_analytics: UA-79603429-1

social:
  #github: https://github.com/
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/allymonger
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/alanahbanana__
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
